version: beta-{build}-{branch}
image: Visual Studio 2017

init:
  - ps: Update-AppveyorBuild -Version "beta-$($env:appveyor_repo_commit.substring(0,7))-master"

cache:
  - packages -> **\packages.config
  - PSTaskDialog

install:
  - nuget restore

before_build:
  - ps: "\"#define BETA\\n\" + (Get-Content \"Fire\\HotkeyHandler.cs\" -Raw).replace(\"$COMMIT_HASH$\", \"$($env:appveyor_repo_commit.substring(0,7))\") | Set-Content \"Fire\\HotkeyHandler.cs\""

build:
  project: Fire.sln

artifacts:
  - path: Fire\bin\Debug\Fire.exe
  - path: Fire\bin\Debug\Fire.pdb
