version: beta-{build}-{branch}
image: Visual Studio 2017

init:
- ps: Update-AppveyorBuild -Version "beta-$($env:appveyor_repo_commit.substring(0,7))-master"

cache:
  - packages -> **\packages.config
  - PSTaskDialog

install:
  - nuget restore

assembly_info:
  patch: true 
  file: AssemblyInfo.* 
  assembly_version: "1.0.0.{version}" 
  assembly_file_version: "1.0.0.{version}" 
  assembly_informational_version: "1.0.0.{version}"

build:
  project: Fire.sln

artifacts:
  - path: Fire\bin\Debug\Fire.exe
  - path: Fire\bin\Debug\Fire.pdb
