version: beta-{build}-{branch}
image: Visual Studio 2017

cache:
  - packages -> **\packages.config

install:
  - nuget restore

build:
  project: Fire.sln

artifacts:
  - path: Fire\bin\Debug\Fire.exe